font_size 11.0

hide_window_decorations yes
confirm_os_window_close 0

background #0D1117
foreground #F8F8F2

window_padding_width 0
placement_strategy top-left

remember_window_size no
initial_window_width 900
initial_window_height 620

enable_audio_bell no
cursor_blink_interval 0

shell_integration no-cursor
