# Переменные окружения для BSPWM
export XDG_CURRENT_DESKTOP=GNOME
export XDG_SESSION_TYPE=x11
export XDG_SESSION_DESKTOP=bspwm

# Запуск portal для файловых диалогов в браузере
/usr/lib/xdg-desktop-portal-gtk &
sleep 1
/usr/lib/xdg-desktop-portal &
sleep 1

exec bspwm
